# Generated by Django 4.2.5 on 2023-10-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='technology',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
