# Generated by Django 4.2.5 on 2023-10-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_myproject_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='technology',
            field=models.CharField(max_length=50),
        ),
    ]
